object Versions {

    const val gradlePlugin = "4.2.1"
    const val kotlin = "1.7.0"
    const val material = "1.7.0"
    const val constraintLayout = "2.1.4"
    const val jUnit = "4.13.2"
    const val appcompat = "1.3.1"
    const val mviCore = "1.3.1"
    const val composeThemeAdapter = "1.2.1"
    const val appCompatTheme = " 0.25.1"
    const val hilt = "2.38.1"
    const val retrofit = "2.9.0"
    const val coil = "2.2.2"
    const val lifecycle = "2.4.0"
    const val lifeCycleKtx = "2.3.1"
    const val compose = "1.3.1"
    const val extJunit = "1.1.4"
    const val espresso = "3.5.0"
    const val splashScreen = "1.0.0"
    const val navigation = "2.4.0-beta02"
    const val dataStore = "1.0.0"
    const val composeVersion = "1.0.1"
    const val coroutine = "1.3.9"
    const val okhttp = "3.14.7"
    const val gson = "2.8.6"
}
